name: Create new release with changelog

permissions:
  contents: write
  pull-requests: write

on:
  pull_request_target:
    types: [closed]

jobs:
  release:
    uses: timkrebs/github-workflows/.github/workflows/gh-create-release.yml@v1